### ISSUE TITLE
Не происходит активация игры/клейма, не изменяется баланс по логу скрипта и фактически в приложении

### ISSUE THREAD

**Issue by joden95** [AlexKrutoy/DiamoreCoBot#1]
По логу скрипта происходит игра и типо начисляются токеты, однако баланс при этом не меняется, ни в моменте фиксации лога, ни черезе час, ни через 2 часа и т.д.
Если при этом зайти в самое приложение физически, то отката игры нету, она даже и не запускалась.
На скрине можно проследить на примере одной сессии, которая имеет баланс 4312....но так со всеми работает

![Screenshot_2](https://github.com/AlexKrutoy/DiamoreCoBot/assets/159123995/d8193970-c3e7-443f-b537-6758ff42be9e)

**Comment by boika** [comment]
Да, бот сейчас не работает.

**Comment by AlexKrutoy** [comment]
пофикшено
