### ISSUE TITLE
Unknown error: 'dailyBonusAvailable'

### ISSUE THREAD

**Issue by Pawansingh333** [AlexKrutoy/DiamoreCoBot#10]
Unknown error: 'dailyBonusAvailable'

**Comment by Nord1cWarr1or** [comment]
Подтверждаю. Из-за этой ошибки бот ничего не собирает

**Comment by ForsakenBob** [comment]
Аналогично все, ждем фикс.

**Comment by Pawansingh333** [comment]
please fix

**Comment by hamedalinejad** [comment]
i get
Unknown error: 'dailyBonusAvailable'
