### ISSUE TITLE
Sir, the software is not working. Can you update it

### ISSUE THREAD

**Issue by hardwin1014** [AlexKrutoy/DiamoreCoBot#6]

**Comment by prognt** [comment]
works fine

```
2024-07-25 13:51:01 | INFO     | 253 - 2162 | Game on cooldown
2024-07-25T08:51:02.763492800Z 2024-07-25 13:51:02 | INFO     | 263 - 2162 | sleep 4.33 min
2024-07-25T08:55:24.339259200Z 2024-07-25 13:55:24 | INFO     | 197 - 2162 | Balance - 95304
2024-07-25T08:55:30.836728400Z 2024-07-25 13:55:30 | INFO     | 250 - 2162 | Played game, got - 732 diamonds, balance - 96036
```

**Comment by hardwin1014** [comment]
> works fine
> 
> ```
> 2024-07-25 13:51:01 | INFO     | 253 - 2162 | Game on cooldown
> 2024-07-25T08:51:02.763492800Z 2024-07-25 13:51:02 | INFO     | 263 - 2162 | sleep 4.33 min
> 2024-07-25T08:55:24.339259200Z 2024-07-25 13:55:24 | INFO     | 197 - 2162 | Balance - 95304
> 2024-07-25T08:55:30.836728400Z 2024-07-25 13:55:30 | INFO     | 250 - 2162 | Played game, got - 732 diamonds, balance - 96036
> ```
And I ran it like this
![image](https://github.com/user-attachments/assets/d051ea71-a34b-4478-8950-8f417976675d)

**Comment by hardwin1014** [comment]
> works fine
> 
> ```
> 2024-07-25 13:51:01 | INFO     | 253 - 2162 | Game on cooldown
> 2024-07-25T08:51:02.763492800Z 2024-07-25 13:51:02 | INFO     | 263 - 2162 | sleep 4.33 min
> 2024-07-25T08:55:24.339259200Z 2024-07-25 13:55:24 | INFO     | 197 - 2162 | Balance - 95304
> 2024-07-25T08:55:30.836728400Z 2024-07-25 13:55:30 | INFO     | 250 - 2162 | Played game, got - 732 diamonds, balance - 96036
> ```

There is something wrong with my session, thank you
